# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F-4UmaCnB2PGfH3xAFP36JG96ig_vI23
"""

1+1

10+5



"""105"""



"""Here is my first opperation"""

